---
- name: Deploy Calculator App with Docker
  hosts: MyHost
  become: no
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Pull Docker image
      docker_image:
        name: deomoney721/mini_calculator
        tag: latest
        source: pull

    - name: Stop and remove existing container (if any)
      docker_container:
        name: scientific-calculator_mini-project
        state: absent

    - name: Run Docker container
      docker_container:
        name: scientific-calculator_mini-project
        image: deomoney721/mini_calculator:latest
        state: started