---
- name: Deploy Calculator App with Docker
  hosts: MyHost
  become: no
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Pull Docker Image
      command: docker pull deomoney721/mini_calculator:latest

    - name: Run Docker Container
      command: docker run -d --name scientific-calculator_mini-project deomoney721/mini_calculator:latest